services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
    volumes: [".:/code"]
    working_dir: /code
    env_file: [.env]
    depends_on: [postgres, redis]
    ports: ["8000:8000"]

  worker:
    build: .
    command: celery -A app.celery_app.celery worker -l info --concurrency=2
    volumes: [".:/code"]
    working_dir: /code
    env_file: [.env]
    depends_on: [postgres, redis]

  beat:
    build: .
    command: celery -A app.celery_app.celery beat -l info
    volumes: [".:/code"]
    working_dir: /code
    env_file: [.env]
    depends_on: [postgres, redis]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5433:5432"]  # expose locally on 5433
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [postgres]

volumes:
  pgdata:
